# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


minecraft:
  gamemode: 'survival'
  motd: 'Your super-cool, super-kube, minecraft server' # Message of the Day
  port: 25565
  image:
    name: itzg/minecraft-server
    tag: latest

volume:
  storage: 10Gi
  storageClassName: 'longhorn'

resources:
  limits:
    memory: 2Gi
    cpu: "1"
  requests:
    memory: 1.5Gi
    cpu: "0.5"

serviceAccount:
  create: true