# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


minecraft:
  gamemode: 'survival'
  motd: 'Your super-cool, super-kube, minecraft server' # Message of the Day
  port: 25565

volume:
  storage: 3Gi
  class: 'longhorn'

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi

serviceAccount:
  create: true