---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: {{ .Values.volume.path }} 
  nodeSelector:
    kubernetes.io/os: "linux"
    disktype: ssd

